# agents.py
import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

load_dotenv()

# ══════════════════════════════════════════════════════
# SHARED LLM
# ══════════════════════════════════════════════════════

llm = ChatGroq(
    api_key=os.getenv("GROQ_API_KEY"),
    model="openai/gpt-oss-120b",    # ← this is in your list
    temperature=0.3
)

parser = StrOutputParser()

# ══════════════════════════════════════════════════════
# AGENT 1 — Research Agent
# ══════════════════════════════════════════════════════

research_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a research specialist.
Your job is to research a topic thoroughly.
For any topic given:
1. Break it into 3 specific research questions
2. Answer each question with 2-3 sentences of factual information
3. Format your response clearly with each question and answer
Be factual, specific and informative."""),
    ("human", "Research this topic thoroughly: {topic}")
])

research_chain = research_prompt | llm | parser


# ══════════════════════════════════════════════════════
# AGENT 2 — Summariser Agent
# ══════════════════════════════════════════════════════

summariser_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a summarisation specialist.
Your job is to read raw research notes and extract the most important information.
Always output exactly 5 bullet points.
Each bullet point should be one clear, factual, specific sentence.
Format: Start each point with •"""),
    ("human", "Summarise these research notes into 5 key bullet points:\n\n{research}")
])

summariser_chain = summariser_prompt | llm | parser


# ══════════════════════════════════════════════════════
# AGENT 3 — Critic Agent
# ══════════════════════════════════════════════════════

critic_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a critical reviewer and quality specialist.
Your job is to review a research summary and improve it.
For any summary given:
1. Identify 2 weaknesses or gaps in the summary
2. Suggest specific improvements for each weakness
3. Provide an improved version of the summary with your suggestions applied
Format your response in three clear sections:
WEAKNESSES, IMPROVEMENTS, IMPROVED SUMMARY"""),
    ("human", """Review and improve this research summary:
Topic: {topic}
Summary:
{summary}""")
])

critic_chain = critic_prompt | llm | parser


# ══════════════════════════════════════════════════════
# AGENT 4 — Report Writer Agent
# ══════════════════════════════════════════════════════

report_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a professional report writer.
Your job is to take research notes and write a polished, structured report.

Always format your report exactly like this:

# [TOPIC] - Research Report

## Executive Summary
[2-3 sentence overview of the most important findings]

## Key Findings
[5 bullet points of the most important facts]

## Challenges & Opportunities
[3 bullet points on challenges, 3 on opportunities]

## Conclusion
[2-3 sentences wrapping up with a forward-looking statement]

---
Report generated by AI Research Assistant"""),
    ("human", """Write a professional report based on this research:
Topic: {topic}
Raw Research: {research}
Refined Summary: {refined_summary}""")
])

report_chain = report_prompt | llm | parser


# ══════════════════════════════════════════════════════
# FULL 4-AGENT PIPELINE
# ══════════════════════════════════════════════════════

def run_research_pipeline(topic: str) -> dict:
    """
    Full 4-agent pipeline:
    Agent 1 - Research
    Agent 2 - Summarise
    Agent 3 - Critique and improve
    Agent 4 - Write final report
    """
    print(f"\n{'='*55}")
    print(f"🔍 Starting research on: {topic}")

    # Agent 1 — Research
    print("\n⚙️  Agent 1 (Research) working...")
    raw_research = research_chain.invoke({"topic": topic})
    print("✅ Agent 1 complete")

    # Agent 2 — Summarise
    print("\n⚙️  Agent 2 (Summariser) working...")
    summary = summariser_chain.invoke({"research": raw_research})
    print("✅ Agent 2 complete")

    # Agent 3 — Critique
    print("\n⚙️  Agent 3 (Critic) working...")
    critique = critic_chain.invoke({
        "topic":   topic,
        "summary": summary
    })
    print("✅ Agent 3 complete")

    # Agent 4 — Write Report
    print("\n⚙️  Agent 4 (Report Writer) working...")
    report = report_chain.invoke({
        "topic":           topic,
        "research":        raw_research,
        "refined_summary": critique
    })
    print("✅ Agent 4 complete")

    return {
        "topic":    topic,
        "research": raw_research,
        "summary":  summary,
        "critique": critique,
        "report":   report
    }


def save_report(topic: str, report: str) -> str:
    """Save the report to a text file."""
    filename = topic.replace(" ", "_").lower() + "_report.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n💾 Report saved to: {filename}")
    return filename


# ══════════════════════════════════════════════════════
# TEST
# ══════════════════════════════════════════════════════

if __name__ == "__main__":
    result = run_research_pipeline("AI startups in India 2026")

    print("\n" + "="*55)
    print("📚 RAW RESEARCH:")
    print(result["research"])

    print("\n" + "="*55)
    print("📋 SUMMARY:")
    print(result["summary"])

    print("\n" + "="*55)
    print("🔍 CRITIQUE:")
    print(result["critique"])

    print("\n" + "="*55)
    print("📄 FINAL REPORT:")
    print(result["report"])

    # Save report to file
    save_report(result["topic"], result["report"])